name: pytorch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - absl-py=0.7.1=py37_0
  - asn1crypto=1.3.0=py37_0
  - astor=0.7.1=py_0
  - attrs=19.1.0=py37_1
  - backcall=0.1.0=py37_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_7
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - bzip2=1.0.8=h516909a_2
  - c-ares=1.15.0=h14c3975_1001
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - cffi=1.12.3=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - cloudpickle=1.2.2=py_0
  - cpuonly=1.0=0
  - cryptography=2.8=py37h1ba5d50_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37h7b6447c_0
  - dask-core=2.10.1=py_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0.2=ha0c5888_2
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_1005
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_7
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - gnutls=3.5.19=h2a4e5f8_1
  - graphite2=1.3.13=hf484d3e_1000
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_7
  - h5py=2.8.0=py37h3010b51_1003
  - harfbuzz=1.9.0=he243708_1001
  - hdf5=1.10.2=hc401514_3
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_0
  - imageio=2.6.1=py37_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.1=py37h39e3cac_0
  - ipython=7.5.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.13.3=py37_0
  - jinja2=2.10.1=py37_0
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.0.1=py37_0
  - jupyter_client=5.2.4=py37_0
  - jupyter_core=4.4.0=py37_0
  - keras=2.2.4=py37_1
  - keras-applications=1.0.7=py_1
  - keras-preprocessing=1.0.9=py_1
  - kiwisolver=1.1.0=py37he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1000
  - libgpuarray=0.7.6=h14c3975_1003
  - libiconv=1.15=h516909a_1005
  - libopencv=3.4.2=hb342d67_1
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.8.0=h8b12597_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - mako=1.0.10=py_0
  - markdown=2.6.11=py_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.0=py37h5429711_0
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.12=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - mock=3.0.5=py37_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.3=0
  - networkx=2.4=py_0
  - ninja=1.9.0=py37hfd86e86_0
  - notebook=5.7.8=py37_0
  - numpy-base=1.16.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1g=h516909a_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.4.0=py_0
  - patsy=0.5.1=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.1.1=py37_0
  - pixman=0.38.0=h516909a_1003
  - prometheus_client=0.6.0=py37_0
  - prompt_toolkit=2.0.9=py37_0
  - protobuf=3.8.0=py37he1b5a44_0
  - psutil=5.6.7=py37h7b6447c_0
  - ptyprocess=0.6.0=py37_0
  - py-opencv=3.4.2=py37hb342d67_1
  - pycparser=2.19=py37_0
  - pygments=2.4.2=py_0
  - pygpu=0.7.6=py37h3010b51_1000
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.14.11=py37h7b6447c_0
  - pysocks=1.7.1=py37_0
  - python=3.7.3=h0371630_0
  - python-dateutil=2.8.0=py37_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.2.0=cuda100py37h938c94c_0
  - pytorch-cpu=1.1.0=py3.7_cpu_0
  - pytz=2019.1=py_0
  - pywavelets=1.1.1=py37h7b6447c_0
  - pyyaml=5.1.1=py37h516909a_0
  - pyzmq=18.0.0=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_1
  - scikit-image=0.15.0=py37he6710b0_0
  - scikit-learn=0.22.1=py37hd81dba3_0
  - seaborn=0.10.0=py_0
  - send2trash=1.5.0=py37_0
  - setuptools=41.0.1=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.28.0=h7b6447c_0
  - statsmodels=0.11.1=py37h8f50634_1
  - tensorflow=1.13.1=py37_0
  - tensorflow-estimator=1.13.0=py_0
  - termcolor=1.1.0=py_2
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py37_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - torchvision=0.4.0=py37_cpu
  - torchvision-cpu=0.3.0=py37_cuNone_1
  - tornado=6.0.2=py37h7b6447c_0
  - tqdm=4.42.0=py_0
  - traitlets=4.3.2=py37_0
  - urllib3=1.25.8=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.15.4=py_0
  - wheel=0.33.4=py37_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=h14c3975_1001
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - adversarial-robustness-toolbox==1.2.0
    - alembic==1.4.0
    - arviz==0.7.0
    - autograd==1.3
    - blessings==1.7
    - boltons==20.0.0
    - cachetools==4.0.0
    - cftime==1.1.0
    - click==7.0
    - colorama==0.4.3
    - colored==1.4.2
    - configparser==4.0.2
    - databricks-cli==0.9.1
    - docker==4.1.0
    - enum34==1.1.6
    - filelock==3.0.12
    - flask==1.1.1
    - funcsigs==1.0.2
    - future==0.18.2
    - gitdb2==2.0.6
    - gitpython==3.0.5
    - google-auth==1.11.0
    - google-auth-oauthlib==0.4.1
    - gorilla==0.3.0
    - gpustat==0.6.0
    - grpcio==1.26.0
    - gunicorn==20.0.4
    - horovod==0.19.1
    - importlib-metadata==1.5.0
    - ipywidgets==7.5.1
    - itsdangerous==1.1.0
    - keras-resnet==0.2.0
    - lasagne==0.2.dev1
    - mlflow==1.6.0
    - more-itertools==8.2.0
    - munch==2.5.0
    - netcdf4==1.5.3
    - numpy==1.18.1
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - opt-einsum==3.1.0
    - packaging==20.1
    - pandas==0.25.0
    - pillow==5.4.1
    - pluggy==0.13.1
    - pretrainedmodels==0.7.4
    - prometheus-flask-exporter==0.12.1
    - py==1.8.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pymc3==3.8
    - pyro-api==0.1.1
    - pyro-ppl==1.2.1
    - pystopwatch2==0.1.1
    - pytest==5.3.5
    - python-editor==1.0.4
    - python-resize-image==1.1.19
    - querystring-parser==1.2.4
    - ray==0.8.1
    - redis==3.4.1
    - requests-oauthlib==1.3.0
    - robustml==0.0.3
    - rsa==4.0
    - scipy==1.4.1
    - setgpu==0.0.7
    - simplejson==3.17.0
    - sklearn==0.0
    - smmap2==2.0.5
    - sqlalchemy==1.3.13
    - sqlparse==0.3.0
    - tabulate==0.8.6
    - tensorboard==1.14.0
    - tensorboardx==2.0
    - theano==0.7.0
    - theconf==0.1.3
    - torch==1.4.0
    - warmup-scheduler==0.1.1
    - websocket-client==0.57.0
    - widgetsnbextension==3.5.1
    - xarray==0.15.0
    - zipp==2.1.0
prefix: /home/meng/anaconda3/envs/pytorch

